### ISSUE TITLE
Opt-out escaping

### ISSUE THREAD

**Issue by jquesada2016** [Atrociously/stilts#2]
I saw in the docs that `stilts` has opt-in HTML escaping. Is there anything in particular from stopping the crate from defaulting to the safer opt-out approach?

In `askama`, it's enabled implicitly via the template's file extension, or explicitly via the file or macro config.

**Comment by Atrociously** [comment]
Hi! First, thanks for opening an issue, second sorry for a late response university has started back up and I'm not as active on github as a result. To answer your question, there are a few technical hurdles, first I'd have to add file type recognition, and second the way the code is generated right now essentially uses the write! macro and to escape you call a function on your type that wraps its Display implementation. To do opt-out I'd have to add file type recognition and then default to wrapping the Display implementation and adding a function to disable that. I think it is possible but I was lazy and went with an easier option.

**Comment by Atrociously** [comment]
Reading back over my response I feel I didn't explain things properly. Essentially any expression that you want to render to the template must evaluate to a type that implements Display. In order to escape you call a function that returns a type who's implementation of Display is a wrapper around the type you are calling it on which adds escaping. In order to do opt-out I'd have to shift that to automatically generate code that wraps the Display implementation and add a function to opt out of that, which I think is possible and I would like to do but I didn't mess around with it out of laziness. If you have further questions please feel free to ask!

**Comment by Atrociously** [comment]
I just released an update f8f8b1c that adds opt-out escaping in a way that I am satisfied with you can check it out if you'd like to, but I'm going to close this issue thanks again for asking!
