### ISSUE TITLE
Consider allowing nested templates

### ISSUE THREAD

**Issue by jquesada2016** [Atrociously/stilts#9]
Currently, the only way to nest templates is to call the inner templates' `.render()` function:

```rust
#[derive(stilts::Template)]
#[path(/* ... */)]
struct TemplateA {}

#[derive(stilts::Template)]
#[path(/* ... */)]
struct TemplateB {}
```

```html
<!-- in TemplateB's template file -->
{% TemplateA::default() %}
```

The only way to make this work currently is:

```html
<!-- in TemplateB's template file -->
{% TemplateA::default().render() %}
```

This is kind of a problem because for each `.render()` invocation, we're allocating a new string. It would be quite nice if instead, the Template deriving struct would provide an alternative method that would return a pre-escaped type that implements `Display`, but hasn't created an intermediate string.

Maybe something like:

```rust
trait Template {
  /* ... */
  fn as_display(&self) -> DisplayTemplate<'_> { TemplateDisplay(self) }
}
```

**Comment by Atrociously** [comment]
Hi, does the [include](https://atrociously.github.io/stilts/language/inheritance_expressions.html#include) system do what you ask? Now with improvements you can write code that includes another template and sets defaults or values as you would a struct.

Template B
```html
{% include "template_a.html" { ..Default::default() } %}
```

this would not create an intermediate string, and you can use this format to specify other fields if you wish.

There is another alternative aside from that if you want to dive deeper into the way the render trait works you can use the [fmt](https://docs.rs/stilts/latest/stilts/trait.Template.html#tymethod.fmt) method instead of render.

```html
{% TemplateA::default().fmt(_w); %}
```

Notice that this is a statement and **not** an expression this will also not create an extra string.

**Comment by Atrociously** [comment]
Let me know if neither of these options solve your use case!

**Comment by jquesada2016** [comment]
Hey, sorry for not responding. I had forgotten!

Option 1 does not work because I'm using components embedded within the struct itself, and including causes the fields to be required on the struct, reducing ergonomics for us. We use `typed_builder`, which is where we're trying to save on allocations.

Option 2 definitely works, but it's extremely fishy, as it's completely unheigenic. Is there any way either some syntax can be added to make this more first-class? Or add documentation that this is something that is planned to be supported and won't break at any minor release, since we'd be relying on the internal macro's output codegen

**Comment by Atrociously** [comment]
I agree that the second option is fishy, you could set the `writer_name` config option to overwrite the output of the macro. This option should never change, however I'm still not extremely satisfied with that option. Now that I understand your need for runtime template access from within another template I absolutely will be adding a `display` method to the template trait which does as you described.

**Comment by Atrociously** [comment]
Alright I have added this method to the latest 0.3.3 version available now it was a very straightforward addition and I think worthwhile.

**Comment by jquesada2016** [comment]
Wow, thanks a ton! This will help on memory allocations a lot!
